### PR TITLE
Adding Makefile for running tests via 'make test'

### PR DESCRIPTION
**Pull request by waja**
This can be used for local development and even for running at travis-ci.

### CODE REVIEW

**Comment by fradelg** [comment]
Thanks for the test script!

I don't have any linter or syntax checker for bash enabled in my text editor so it will be useful to test the code after every push.

**Comment by waja** [comment]
You can also make use of [travis-ci](travis-ci.org). For an example see https://github.com/Cyconet/docker-wowza-streaming-engine-linux-loadbalancer/blob/master/.travis.yml

**Comment by fradelg** [comment]
Done! 

I have changed the scripts to fulfil the modern bash syntax requirements. 

Report any issues you find when testing

**Comment by waja** [comment]
I also recommend to use "master" and "development" while master can live at docker hub as "latest" and "development" as "development". So you don't break "latest" with every commit necessarily. :o)

**Comment by fradelg** [comment]
I agree. Besides, I am going to use tags in repo to match tags in images. So 1.0.0 will be the original image with the cleanup script patched

**Comment by waja** [comment]
Great!

**Pull request merged**
